// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using geneticAlgorithmsApp.src.Data;

namespace geneticAlgorithmsApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211113181032_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("geneticAlgorithmsApp.src.Models.Curso", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("geneticAlgorithmsApp.src.Models.Disciplina", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("DisciplinaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Disciplina");
                });

            modelBuilder.Entity("geneticAlgorithmsApp.src.Models.Local", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Local");
                });

            modelBuilder.Entity("geneticAlgorithmsApp.src.Models.Professor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("geneticAlgorithmsApp.src.Models.Turma", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CursoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DiaDaSemana")
                        .HasColumnType("int");

                    b.Property<string>("DisciplinaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan>("HorarioFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("time");

                    b.Property<string>("LocalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfessorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("LocalId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Turma");
                });

            modelBuilder.Entity("geneticAlgorithmsApp.src.Models.Disciplina", b =>
                {
                    b.HasOne("geneticAlgorithmsApp.src.Models.Disciplina", null)
                        .WithMany("PreRequisitos")
                        .HasForeignKey("DisciplinaId");
                });

            modelBuilder.Entity("geneticAlgorithmsApp.src.Models.Turma", b =>
                {
                    b.HasOne("geneticAlgorithmsApp.src.Models.Curso", "Curso")
                        .WithMany("Turmas")
                        .HasForeignKey("CursoId");

                    b.HasOne("geneticAlgorithmsApp.src.Models.Disciplina", "Disciplina")
                        .WithMany("Turmas")
                        .HasForeignKey("DisciplinaId");

                    b.HasOne("geneticAlgorithmsApp.src.Models.Local", "Local")
                        .WithMany("Turmas")
                        .HasForeignKey("LocalId");

                    b.HasOne("geneticAlgorithmsApp.src.Models.Professor", "Professor")
                        .WithMany("Turmas")
                        .HasForeignKey("ProfessorId");

                    b.Navigation("Curso");

                    b.Navigation("Disciplina");

                    b.Navigation("Local");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("geneticAlgorithmsApp.src.Models.Curso", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("geneticAlgorithmsApp.src.Models.Disciplina", b =>
                {
                    b.Navigation("PreRequisitos");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("geneticAlgorithmsApp.src.Models.Local", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("geneticAlgorithmsApp.src.Models.Professor", b =>
                {
                    b.Navigation("Turmas");
                });
#pragma warning restore 612, 618
        }
    }
}
